server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.yml
    default-schema: public
    contexts: migrated

jwt:
  secret-key: "secret_key"
  accessTokenExpirationMs: 600000
  refreshTokenExpirationMs: 1800000

springfox:
  documentation:
    swagger:
      v2:
        enabled: true
      ui:
        enabled: true

